[package]
name = "configurable"
version = "0.1.0"
edition = "2021"

[lib]
name = "configurable"
path = "lib/lib.rs"


[[bin]]
name="admin_panel"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
